# source:
# https://towardsdatascience.com/how-to-run-postgresql-using-docker-15bf87b452d4

version: "3.8"

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photocontest
    ports:
      - "5434:5432"
    # volumes:
      # - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      # - pg_data:/var/lib/postgresql/data/

  # volumes:
  #   pg_data:
