openapi: 3.0.1
info:
  title: Photo Contest
  description: "This is Glints PTB1 Final Project.
    Github project at [https://github.com/ptbglints/photocontest](https://github.com/ptbglints/photocontest)
    For this sample, you can use the api key `special-key` to test the authorization filters."
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: "Find more info here"
  url: "https://example.com"
servers:
  - url: http://localhost:8000/api
  - url: https://ptb-photocontest.herokuapp.com/api
tags:
  - name: User
  - name: Profile
  - name: Photos

paths:
  /users:
    get:
      tags:
        - User
      summary: Get all user
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
      operationId: getMany
      # parameters:
      #   - name: id
      #     in: path
      #     description: User ID
      #     required: true
      #     schema:
      #       type: integer
      #       format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/User"

  /users/signup:
    post:
      tags:
        - User
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "broto"
                email:
                  type: string
                  example: "broto@mantab.io"
                password:
                  type: string
                  example: "Pass123?"
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /users/login:
    post:
      tags:
        - User
      summary: User login
      # description: This can only be done by the logged in user.
      # operationId: createUser
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "arman"
                password:
                  type: string
                  example: "Pass123?"
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /users/profile/userid/{id}:
    get:
      tags:
        - Profile
      summary: Gets profile by userId
      # description:
      # operationId: getUserById
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
            example: 4
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"

  /users/profile/:
    put:
      tags:
        - Profile
      summary: Update users own profile
      # description: This can only be done by the logged in user.
      # operationId: createUser
      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 4
                name:
                  type: string
                  example: "Arman Maulalan"
                # address:
                #   type: string
                #   example: 'Jl. Pinang Kayu no.30 Bandung'
                # profilephoto:
                #   type: string
                # coverphoto:
                #   type: string
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /users/profile/username/{username}:
    get:
      tags:
        - Profile
      summary: Gets specific profile by Username
      # description:
      # operationId: getUserById
      parameters:
        - name: username
          in: path
          description: User name
          required: true
          schema:
            type: string
            example: "alice"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"

  /photos:
    get:
      tags:
        - Photos
      summary: Get all photos from database with limit
      description: >
        Get all photos from database with limit
      parameters:
      - name: limit
        in: query
        description: limit
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Photos"

  /photos/user/{id}:
    get:
      tags:
        - Photos
      summary: Get all photos from a specific user
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
            example: 4
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Photos"

  /photos/{photoId}:
    get:
      tags:
        - Photos
      summary: Get a specific photo by photo ID
      parameters:
        - name: photoId
          in: path
          description: photo ID
          required: true
          schema:
            type: integer
            format: int64
            example: 4
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Photos"

  /photos/upload:
    post:
      tags:
        - Photos
      summary: Upload photo to collection User
      description: Logged user only
      operationId: uploadePhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'Standing & terbang'
                description:
                  type: string
                  example: 'Lagi liburan di Papua New Guinea'
                user-photo:
                  type: string
                  format: binary
                tag:
                  type: string
                  example: 'sport,bunga,ikan,bekasi'

      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
        email:
          type: string
        password:
          type: string
          minLength: 8
          maxLength: 254
        role:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Profile:
      type: object
      properties:
        name:
          type: string
        addres:
          type: string
        profilePhoto:
          type: string
        coverPhoto:
          type: string
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Photos:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        path:
          type: string
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
